export const DATASET_VERSION = 1;

export const chapters = [
  {
    id: 1,
    title: 'Chương 1: Bối cảnh lịch sử',
    description: 'Việt Nam dưới ách thống trị của thực dân Pháp',
    icon: 'flag',
    questions: [
      {
        id: 1,
        term: 'Thực dân Pháp xâm lược Việt Nam',
        definition: 'Năm 1858, thực dân Pháp bắt đầu xâm lược Việt Nam và biến nước ta thành thuộc địa.',
        quiz: {
          question: 'Thực dân Pháp xâm lược Việt Nam vào năm nào?',
          options: ['1858', '1862', '1884', '1945'],
          correct: 0,
        },
        fillAnswer: 'Thực dân Pháp xâm lược Việt Nam vào năm ______',
        answer: '1858',
      },
      {
        id: 2,
        term: 'Hậu quả của thực dân Pháp',
        definition: 'Việt Nam bị chia làm 3 kỳ: Trung Kỳ, Nam Kỳ và Bắc Kỳ.',
        quiz: {
          question: 'Thực dân Pháp chia Việt Nam thành mấy kỳ?',
          options: ['2 kỳ', '3 kỳ', '4 kỳ', '5 kỳ'],
          correct: 1,
        },
        fillAnswer: 'Thực dân Pháp chia Việt Nam thành ______',
        answer: '3 kỳ',
      },
      {
        id: 3,
        term: 'Các phong trào yêu nước',
        definition: 'Các phong trào yêu nước như Cần Vương, Yên Thế, Đông Du đều thất bại.',
        quiz: {
          question: 'Phong trào Cần Vương diễn ra vào năm nào?',
          options: ['1885', '1898', '1915', '1925'],
          correct: 0,
        },
        fillAnswer: 'Phong trào Cần Vương diễn ra năm ______',
        answer: '1885',
      },
      {
        id: 4,
        term: 'Nguyễn Ái Quốc ra đi',
        definition: 'Ngày 5/6/1911, Nguyễn Ái Quốc rời bến cảng Nhà Rồng.',
        quiz: {
          question: 'Nguyễn Ái Quốc ra đi từ bến cảng nào?',
          options: ['Bến Nhà Rồng', 'Bến Hải Phòng', 'Bến Sài Gòn', 'Bến Đà Nẵng'],
          correct: 0,
        },
        fillAnswer: 'Nguyễn Ái Quốc ra đi từ ______',
        answer: 'Bến Nhà Rồng',
      },
      {
        id: 5,
        term: 'Mục tiêu của Nguyễn Ái Quốc',
        definition: 'Tìm đường cứu nước và giải phóng dân tộc.',
        quiz: {
          question: 'Mục tiêu chính của Nguyễn Ái Quốc khi ra đi là gì?',
          options: ['Tìm việc làm tốt', 'Tìm đường cứu nước', 'Học tập nghệ thuật', 'Kinh doanh'],
          correct: 1,
        },
        fillAnswer: 'Mục tiêu chính là ______',
        answer: 'Tìm đường cứu nước',
      },
    ],
  },
  {
    id: 2,
    title: 'Chương 2: Quá trình tìm kiếm đường lối',
    description: 'Hành trình của Nguyễn Ái Quốc tìm kiếm con đường cứu nước',
    icon: 'search',
    questions: [
      {
        id: 1,
        term: 'Năm 1919 - Bản yêu sách của nhân dân An Nam',
        definition: 'Năm 1919, tại Hội nghị Véc-xây, Hồ Chí Minh gửi Bản yêu sách của nhân dân An Nam.',
        quiz: {
          question: 'Năm 1919, Hồ Chí Minh gửi văn kiện gì tại Hội nghị Véc-xây?',
          options: ['Tuyên ngôn độc lập', 'Bản yêu sách', 'Di chúc', 'Lời kêu gọi'],
          correct: 1,
        },
        fillAnswer: 'Gửi ______ tại Hội nghị Véc-xây',
        answer: 'Bản yêu sách',
      },
      {
        id: 2,
        term: 'Hội Việt Nam Cách mạng Thanh niên',
        definition: 'Năm 1925, thành lập Hội Việt Nam Cách mạng Thanh niên tại Quảng Châu.',
        quiz: {
          question: 'Hội Việt Nam Cách mạng Thanh niên được thành lập năm nào?',
          options: ['1924', '1925', '1926', '1927'],
          correct: 1,
        },
        fillAnswer: 'Được thành lập năm ______',
        answer: '1925',
      },
      {
        id: 3,
        term: 'Tác phẩm Đường Kách Mệnh',
        definition: 'Tác phẩm Đường Kách Mệnh được xuất bản nhằm truyền bá tư tưởng cách mạng.',
        quiz: {
          question: 'Tác phẩm nào được xuất bản để truyền bá tư tưởng cách mạng?',
          options: ['Tạp chí Tiên Phong', 'Đường Kách Mệnh', 'Tạp chí Quân Đội', 'Tạp chí Văn Hóa'],
          correct: 1,
        },
        fillAnswer: 'Tác phẩm ______ được xuất bản',
        answer: 'Đường Kách Mệnh',
      },
      {
        id: 4,
        term: 'Tiếp xúc với Chủ nghĩa Mác - Lênin',
        definition: 'Năm 1920, tại Đại hội Đảng Cộng sản Pháp, Hồ Chí Minh tiếp nhận Chủ nghĩa Mác - Lênin.',
        quiz: {
          question: 'Hồ Chí Minh tiếp nhận Chủ nghĩa Mác - Lênin ở đâu?',
          options: ['Pháp', 'Nga', 'Anh', 'Trung Quốc'],
          correct: 0,
        },
        fillAnswer: 'Tiếp nhận ở ______',
        answer: 'Pháp',
      },
    ],
  },
  {
    id: 3,
    title: 'Chương 3: Sự ra đời của Đảng',
    description: 'Quá trình hình thành và thành lập Đảng Cộng sản Việt Nam',
    icon: 'star',
    questions: [
      {
        id: 1,
        term: 'Các tổ chức cộng sản năm 1929',
        definition: 'Năm 1929 xuất hiện 3 tổ chức cộng sản ở Việt Nam.',
        quiz: {
          question: 'Năm 1929 có bao nhiêu tổ chức cộng sản xuất hiện?',
          options: ['1', '2', '3', '4'],
          correct: 2,
        },
        fillAnswer: 'Có ______ tổ chức cộng sản',
        answer: '3',
      },
      {
        id: 2,
        term: 'Hội nghị hợp nhất tại Hồng Kông',
        definition: 'Tháng 2/1930, Hội nghị hợp nhất tại Hồng Kông thành lập Đảng Cộng sản Việt Nam.',
        quiz: {
          question: 'Đảng Cộng sản Việt Nam được thành lập ở đâu?',
          options: ['Việt Nam', 'Hồng Kông', 'Moscow', 'Paris'],
          correct: 1,
        },
        fillAnswer: 'Được thành lập ở ______',
        answer: 'Hồng Kông',
      },
      {
        id: 3,
        term: 'Ngày thành lập Đảng',
        definition: 'Ngày 3/2/1930 là ngày thành lập Đảng Cộng sản Việt Nam.',
        quiz: {
          question: 'Đảng Cộng sản Việt Nam được thành lập ngày nào?',
          options: ['3/2/1930', '2/2/1930', '1/2/1930', '5/2/1930'],
          correct: 0,
        },
        fillAnswer: 'Ngày ______/1930',
        answer: '3/2',
      },
      {
        id: 4,
        term: 'Ý nghĩa của sự ra đời Đảng',
        definition: 'Đảng ra đời đánh dấu bước ngoặt trong quá trình cách mạng Việt Nam.',
        quiz: {
          question: 'Sự ra đời của Đảng có ý nghĩa gì?',
          options: ['Chia rẽ chính trị', 'Bước ngoặt quan trọng', 'Kết thúc chiến tranh', 'Mở rộng kinh tế'],
          correct: 1,
        },
        fillAnswer: 'Là ______ trong lịch sử',
        answer: 'Bước ngoặt',
      },
      {
        id: 5,
        term: 'Chính cương vắn tắt 1930',
        definition: 'Chính cương vắn tắt xác định mục tiêu giải phóng dân tộc, chống phong kiến và chống thực dân.',
        quiz: {
          question: 'Mục tiêu chính của Chính cương vắn tắt năm 1930 là gì?',
          options: ['Phát triển kinh tế', 'Giải phóng dân tộc', 'Xây dựng văn hóa', 'Cải cách giáo dục'],
          correct: 1,
        },
        fillAnswer: 'Mục tiêu là ______',
        answer: 'Giải phóng dân tộc',
      },
    ],
  },
];