export const timelineEvents = [
  {
    year: "1890",
    title: "Khởi nguồn hành trình",
    subtitle: "Sinh ra tại Làng Sen",
    description: "Nguyễn Sinh Cung (Hồ Chí Minh) sinh ra tại Làng Sen, Nghệ An trong bối cảnh đất nước mất độc lập.",
    quote: "Không có gì quý hơn độc lập, tự do.",
    author: "Hồ Chí Minh",
    details: "Từ nền tảng truyền thống gia đình và quê hương.",
  },
  {
    year: "1911",
    title: "Bước ngoặt cuộc đời",
    subtitle: "Bến Nhà Rồng – Ra đi tìm đường cứu nước",
    description: "Ngày 5/6/1911, Nguyễn Ái Quốc rời Sài Gòn trên tàu Amiral Latouche-Tréville.",
    quote: "Muốn cứu nước và giải phóng dân tộc không có con đường nào khác con đường cách mạng.",
    author: "Hồ Chí Minh",
    details: "Trong hành trình, Người quan sát thực tiễn các nước và tiếp xúc với nhiều luồng tư tưởng.",
  },
  {
    year: "1930",
    title: "Đổi mới ánh sáng",
    subtitle: "Thành lập Đảng Cộng sản Việt Nam",
    description: "Tháng 2/1930, Hội nghị hợp nhất tại Hồng Kông thành lập Đảng Cộng sản Việt Nam.",
    quote: "Đảng có vững cách mạng mới thành công.",
    author: "Hồ Chí Minh",
    details: "Đường lối giải phóng dân tộc gắn với mục tiêu lâu dài.",
  },
  {
    year: "1945",
    title: "Mùa thu giải phóng",
    subtitle: "Cách mạng Tháng Tám và Tuyên ngôn Độc lập",
    description: "Cách mạng Tháng Tám thành công, khai sinh nước Việt Nam Dân chủ Cộng hòa.",
    quote: "Nước Việt Nam có quyền hưởng tự do và độc lập.",
    author: "Hồ Chí Minh",
    details: "Độc lập không chỉ là chủ quyền quốc gia mà còn gắn với đời sống nhân dân.",
  },
  {
    year: "1954",
    title: "Chiến thắng vang dội",
    subtitle: "Điện Biên Phủ – Chiến thắng lịch sử",
    description: "Chiến thắng Điện Biên Phủ chứng minh sức mạnh của ý chí độc lập và khát vọng tự do.",
    quote: "Đoàn kết, đoàn kết, đại đoàn kết.",
    author: "Hồ Chí Minh",
    details: "Đây là minh chứng cho đường lối cách mạng đúng đắn của dân tộc.",
  },
  {
    year: "1969",
    title: "Di sản bất diệt",
    subtitle: "Ánh sáng vĩnh cửu",
    description: "Người ra đi nhưng tư tưởng, đạo đức và phong cách vẫn còn mãi với dân tộc.",
    quote: "Vì lợi ích mười năm phải trồng cây, vì lợi ích trăm năm phải trồng người.",
    author: "Hồ Chí Minh",
    details: "Di sản nhấn mạnh việc xây dựng con người mới cho đất nước.",
  },
  {
    year: "Hiện tại",
    title: "Di sản sống động",
    subtitle: "Kim chỉ nam cho đổi mới",
    description: "Trong bối cảnh đổi mới và hội nhập, tư tưởng Hồ Chí Minh tiếp tục được vận dụng.",
    quote: "Tư tưởng Hồ Chí Minh là tài sản tinh thần vô giá của Đảng và dân tộc ta.",
    author: "Đảng Cộng sản Việt Nam",
    details: "Trung tâm vận dụng: phát triển kinh tế, xây dựng văn hóa và đạo đức xã hội.",
  },
];